# Generated by Django 4.2.6 on 2023-10-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='posts',
            new_name='post',
        ),
    ]
